/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author paulo
 */
import javax.swing.*;
import javax.swing.text.*;
import java.awt.*;

public class CacaPalavra extends javax.swing.JFrame {

    /**
     * Creates new form CacaPalavra
     */
    public CacaPalavra() {
        initComponents();
        //busca.setVisible(false);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comeca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l = new javax.swing.JTextArea();
        busca = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        resul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnDesistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela De Jogo");

        comeca.setText("Começar");
        comeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comecaActionPerformed(evt);
            }
        });

        l.setEditable(false);
        l.setColumns(20);
        l.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        l.setRows(5);
        l.setText("Aguardando caça-palavras...");
        jScrollPane1.setViewportView(l);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        resul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel1.setText("Sua busca:");

        btnDesistir.setText("Desistir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comeca)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDesistir))
                                .addComponent(busca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comeca)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscar)
                            .addComponent(btnDesistir))
                        .addGap(81, 81, 81)
                        .addComponent(resul, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  
    
    private final char[][] m = LeitorMatriz.recuperaMatriz("matriz.txt");
    
    private void imprimeMatriz() {
        l.setText("");
	for (int i = 0; i < m.length; i++) {
                for (int j = 0; j < m[1].length; j++) {
                    String txtAnt = l.getText();
                    l.setText(txtAnt.concat(" " + Character.toString(m[i][j]) + " "));
                }
                l.setText(l.getText().concat("\n"));
            }
    }
	
    
    /** CONVERSORES **/
    
   
    //----LINHA---------------------------------------------------------------//
    
    private static String converteLinhaString(char[] linhaMatriz) {
        
	StringBuilder linha = new StringBuilder();
		
	for (char charLinhaMatriz : linhaMatriz) {
            
            linha.append(charLinhaMatriz);
            
	}
		
	return linha.toString();
    }
    
    //---COLUNA---------------------------------------------------------------//
    
    private static String converteColunaString(char[][] m,int coluna) {
        
	StringBuilder colunaDaMatriz = new StringBuilder();
        
        for (int i = 0; i < m[0].length; i++) {
            
            for (int j = 0; j < m.length; j++) {
                
                colunaDaMatriz.append(m[j][i]);
                
            }
            
        }
        
        
	return colunaDaMatriz.toString();
    }
    
    //---DIAGONAL-------------------------------------------------------------//
    
    private static String converteDiagonalString(char[][] m,int linha, int coluna) {
        
        StringBuilder diagonal = new StringBuilder();
        
        int indexColunas = m[linha].length - coluna;
        int indexLinhas = m.length - linha;
        
        int tamanhoDiagonal = (indexColunas <= indexLinhas)? indexColunas:indexLinhas;
        
                
        for (int i = 0; i < tamanhoDiagonal; i++) {
            
            diagonal.append(m[linha][coluna]);
            
            ++linha;
            ++coluna;
            
        }
        
        
        return diagonal.toString();
        
    }
	
    private static String insereSituacao(int lComeco, int cComeco, int lFim, int cFim) {
        
	StringBuilder sb = new StringBuilder();
		
	sb.append("ACHOU ");
	sb.append(lComeco + " ");
	sb.append(cComeco + " ");
	sb.append(lFim + " ");
	sb.append(cFim);
		
	return sb.toString();
    }
	
    private static String linhaNormal(char[][] m, String palavra) {
        
	String situacao = "NAO ACHOU";
        
	for (int i = 0; i < m.length; i++) {
            
		String linhaDaMatriz = converteLinhaString(m[i]);
                
		if(linhaDaMatriz.contains(palavra.toUpperCase())) {
                    
			int cComeco = linhaDaMatriz.indexOf(palavra.toUpperCase());
			situacao = insereSituacao(i, cComeco, i, cComeco + palavra.length()-1);
			break;
                        
		}
	}
		
	return situacao;
    }
	
    private static String linhaInvertida(char[][] m, String palavra) {
	StringBuilder sb = new StringBuilder();
	String situacao = "NAO ACHOU";
		
	sb.append(palavra);
	palavra = sb.reverse().toString();
		
	for (int i = 0; i < m.length; i++) {
		String palavraStr = converteLinhaString(m[i]);
		if(palavraStr.contains(palavra.toUpperCase())) {
			int cComeco = palavraStr.indexOf(palavra.toUpperCase());
			situacao = insereSituacao(i, cComeco + palavra.length()-1, i, cComeco); 
			break;
		}
	}
		
	return situacao;
    }
    
    private static String colunaNormal(char[][] m, String palavra) {
        
        StringBuilder situacao = new StringBuilder("NAO ACHOU");
        
        for (int i = 0; i < m[0].length; i++) {
            
            String colunaDaMatriz = converteColunaString(m,i);
            
            if (colunaDaMatriz.contains(palavra)) {
                
                situacao.delete(0, situacao.length());
                
                int lComeco = colunaDaMatriz.indexOf(palavra.toUpperCase());
                
                situacao.append(insereSituacao(lComeco, i, lComeco + palavra.length()-1, i));
                
                break;
            }
        
        }
        
        
        return situacao.toString();
    }
    
    private static String colunaInvertida(char[][] m, String palavra) {
        
        StringBuilder situacao = new StringBuilder("NAO ACHOU");
        StringBuilder sb = new StringBuilder(palavra);
        
        palavra = sb.reverse().toString();
        
        for (int i = 0; i < m[0].length; i++) {
            
            String colunaDaMatriz = converteColunaString(m,i);
            
            if (colunaDaMatriz.contains(palavra)) {
                
                situacao.delete(0, situacao.length());
                
                int lComeco = colunaDaMatriz.indexOf(palavra.toUpperCase());
                
                situacao.append(insereSituacao(lComeco, i, lComeco + palavra.length()-1, i));
                
                break;
            }
        
        }
        
        return situacao.toString();
    }
    
    private static String diagonalNormal(char[][] m, String palavra) {
        
        StringBuilder situacao = new StringBuilder("NAO ACHOU");
        
        for (int i = 0; i < m.length; i++) {
            
            for (int j = 0; j < m[i].length; j++) {
                
                String diagonal = converteDiagonalString(m,i,j);
            
                if(diagonal.contains(palavra)) {
                  
                  situacao.delete(0, situacao.length());
                
                  int lComeco = diagonal.indexOf(palavra.toUpperCase());
                
                  situacao.append(insereSituacao(lComeco, j, lComeco + palavra.length()-1, j + palavra.length()-1));
                
                  break;
                     
                }
                  
            }
           
        
        }
        
        
        return situacao.toString();
    }
    
    private static String diagonalInvertida(char[][] m, String palavra) {
            
        StringBuilder situacao = new StringBuilder("NAO ACHOU");
        StringBuilder sb = new StringBuilder(palavra);
        
        palavra = sb.reverse().toString();
        
        for (int i = 0; i < m.length; i++) {
            
            for (int j = 0; j < m[i].length; j++) {
                
                String diagonal = converteDiagonalString(m,i,j);
            
                if(diagonal.contains(palavra)) {
                  
                  situacao.delete(0, situacao.length());
                
                  int lComeco = diagonal.indexOf(palavra.toUpperCase());
                
                  situacao.append(insereSituacao(lComeco, j, lComeco + palavra.length()-1, j + palavra.length()-1));
                
                  break;
                    
                    
                }
                  
            }
           
        
        }
        
        
        return situacao.toString();    
        
    }
    
    private void comecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comecaActionPerformed
            if("Aguardando caça-palavras...".equals(l.getText())){
            imprimeMatriz();
        }    
    }//GEN-LAST:event_comecaActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(linhaNormal(m, busca.getText()).length() > 9)
            resul.setText(linhaNormal(m, busca.getText()));
        else if(linhaInvertida(m, busca.getText()).length() > 9)
            resul.setText(linhaInvertida(m, busca.getText()));
        else if(colunaNormal(m, busca.getText()).length() > 9)
            resul.setText(colunaNormal(m, busca.getText()));
        else if(colunaInvertida(m, busca.getText()).length() > 9)
            resul.setText(colunaInvertida(m, busca.getText()));
        else if (diagonalNormal(m, busca.getText()).length() > 9)
            resul.setText(diagonalNormal(m, busca.getText()));
        else if (diagonalNormal(m, busca.getText()).length() > 9)
            resul.setText(diagonalNormal(m, busca.getText()));
        else
            resul.setText("NÃO ACHOU");
        /*String a = "oi";
        String ver = "<html><font color=RED> " + a + " </font></html>";
        resul.setText(ver);*/
    }//GEN-LAST:event_buscarActionPerformed
    
    private static void mudaCor(String palavra){
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CacaPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CacaPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CacaPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CacaPalavra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CacaPalavra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesistir;
    private javax.swing.JTextField busca;
    private javax.swing.JButton buscar;
    private javax.swing.JButton comeca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea l;
    private javax.swing.JLabel resul;
    // End of variables declaration//GEN-END:variables
}
